import os
import shutil
import tempfile
from fastapi import FastAPI, UploadFile, File
from fastapi.responses import FileResponse
from basic_pitch.inference import predict_and_save
from basic_pitch import ICASSP_2022_MODEL_PATH

app = FastAPI()

@app.post("/transcribe")
async def transcribe(audio: UploadFile = File(...)):
    """
    Receives an audio file, runs Basic Pitch inference on it,
    and returns the resulting MIDI file.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        audio_path = os.path.join(tmpdir, audio.filename)
        with open(audio_path, "wb") as buffer:
            shutil.copyfileobj(audio.file, buffer)
        
        # Run Basic Pitch inference
        # The true parameters match the default output flags for basic-pitch
        predict_and_save(
            [audio_path],
            tmpdir,
            save_midi=True,
            sonify_midi=False,
            save_model_outputs=False,
            save_notes=False,
            model_or_model_path=ICASSP_2022_MODEL_PATH,
        )
        
        # The output MIDI filename generated by basic-pitch is usually <filename>_basic_pitch.mid
        base_name = os.path.splitext(audio.filename)[0]
        midi_filename = f"{base_name}_basic_pitch.mid"
        midi_path = os.path.join(tmpdir, midi_filename)
        
        if not os.path.exists(midi_path):
            return {"error": "MIDI generation failed"}
        
        # We need to copy the file out of the tmpdir to return it since the tmpdir will be destroyed.
        # Tempfile in /tmp directory for the docker container
        out_temp = tempfile.NamedTemporaryFile(delete=False, suffix=".mid")
        shutil.copy2(midi_path, out_temp.name)
        out_temp.close()
        
        return FileResponse(out_temp.name, media_type="audio/midi", filename="output.mid")
